//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexOffersFizzBuzz.Models
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlexOffersFizzBuzzModelContainer : DbContext
    {
        /// <summary>
        /// This constructor was created for testing purposes
        /// </summary>
        /// <param name="connectionString"> Db to point to. Must add in Web.Config before use </param>
        public FlexOffersFizzBuzzModelContainer(string connectionString)
            : base("name=" + connectionString)
        {
            
        }

        /// <summary>
        /// This constructor will use the production Db
        /// </summary>
        public FlexOffersFizzBuzzModelContainer()
            : base("name=FlexOffersFizzBuzzModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Operation> Operations { get; set; }
        public virtual DbSet<Type> Types { get; set; }
    }
}
