//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexOffersFizzBuzz.Models
{
    using System.Collections.Generic;
    
    public partial class Operation
    {
        public Operation()
        {
            this.Types = new HashSet<Type>();
        }
    
        public int OperationId { get; set; }
        public int LowNumber { get; set; }
        public int HighNumber { get; set; }
        public string Output { get; set; }
        public string Result { get; set; }
        public System.DateTime DateExecuted { get; set; }
    
        public virtual ICollection<Type> Types { get; set; }
    }
}
